/**
 * <copyright>
 * </copyright>
 *
 * $Id: HbAnnotatedEDataTypeValidator.java,v 1.2 2007/11/14 16:38:34 mtaal Exp $
 */
package org.eclipse.emf.teneo.hibernate.hbmodel.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.teneo.annotations.pannotation.Column;
import org.eclipse.emf.teneo.hibernate.hbannotation.IdBag;
import org.eclipse.emf.teneo.hibernate.hbannotation.Index;
import org.eclipse.emf.teneo.hibernate.hbannotation.TypeDef;
import org.eclipse.emf.teneo.hibernate.hbannotation.Where;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.hibernate.hbmodel.HbAnnotatedEDataType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HbAnnotatedEDataTypeValidator {
	boolean validate();

	boolean validateHbTypeDef(TypeDef value);

	boolean validateHbWhere(Where value);

	boolean validateHbColumns(EList<Column> value);

	boolean validateHbIdBag(IdBag value);

	boolean validateHbIndex(Index value);
}
