/**
 * <copyright>
 * </copyright>
 *
 * $Id: HbAnnotatedEReferenceValidator.java,v 1.2 2007/03/04 21:18:07 mtaal Exp $
 */
package org.eclipse.emf.teneo.hibernate.hbmodel.validation;

import org.eclipse.emf.teneo.hibernate.hbannotation.Cache;
import org.eclipse.emf.teneo.hibernate.hbannotation.Fetch;
import org.eclipse.emf.teneo.hibernate.hbannotation.OnDelete;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.hibernate.hbmodel.HbAnnotatedEReference}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HbAnnotatedEReferenceValidator {
	boolean validate();

	boolean validateHbCache(Cache value);
	boolean validateHbFetch(Fetch value);

	boolean validateHbOnDelete(OnDelete value);
}
