/**
 * <copyright>
 * </copyright>
 *
 * $Id: CollectionOfElementsValidator.java,v 1.1 2007/02/08 23:13:12 mtaal Exp $
 */
package org.eclipse.emf.teneo.hibernate.hbannotation.validation;

import org.eclipse.emf.teneo.annotations.pannotation.FetchType;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.hibernate.hbannotation.CollectionOfElements}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CollectionOfElementsValidator {
	boolean validate();

	boolean validateTargetElement(String value);
	boolean validateFetch(FetchType value);
}
