/**
 * <copyright>
 * </copyright>
 *
 * $Id: FilterValidator.java,v 1.1 2008/04/23 15:44:26 mtaal Exp $
 */
package org.eclipse.emf.teneo.hibernate.hbannotation.validation;


/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.hibernate.hbannotation.Filter}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FilterValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateCondition(String value);
}
