/**
 * <copyright>
 * </copyright>
 *
 * $Id: FilterDefValidator.java,v 1.1 2008/04/23 15:44:26 mtaal Exp $
 */
package org.eclipse.emf.teneo.hibernate.hbannotation.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.teneo.hibernate.hbannotation.ParamDef;

/**
 * A sample validator interface for {@link org.eclipse.emf.teneo.hibernate.hbannotation.FilterDef}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FilterDefValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateDefaultCondition(String value);
	boolean validateParameters(EList<ParamDef> value);
}
